# This yaml config is used to control the order of links in the table of contents.
toc:
    - World
    - Entity
    - TagComponent
    - System
    - Not
    - createComponent
    - createType
    - Types
